config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  #get 'users/:id', to:'tasks#index', as: :user
  
  get 'login', to: 'sessions#new' #ログアウトしたときに必要
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  
  resources :tasks
  resources :users, only: [:new, :create] 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    
    
    validates :content,presence: true, length: { maximum:255 }
    validates :status,presence: true, length: { maximum:10 }
    belongs_to :user #ユーザーとタスクが１対多の関係
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    #nameのバリデーション
    validates :name, presence: true, length: { maximum: 50 }
    #e-mailのバリデーション
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    
    has_secure_password
    #これだけでvalidatioも完了
    
    has_many :tasks #Userから見たときにタスクが複数ある
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    
    
    private
    
    def require_user_logged_in
        unless logged_in?
            redirect_to login_url
        end
    end
    
    def counts(user)
        @count_tasks = user.tasks.count
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = 'ログイン成功です'
      redirect_to root_url 
    else
      flash.now[:danger] = 'ログイン失敗です'
      render :new
      
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      #ログイン成功
      session[:user_id] = @user.id
      return true
    else
      #ログイン失敗
      return
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_task, only: [:show, :destroy, :edit, :update]

  def index
      @tasks = current_user.tasks.order(id: :desc).page(params[:page])
      #binding.pry
  end
  
  def show 
  end

  def new
      @task = current_user.tasks.new
  end

  def create
      @task = current_user.tasks.build(task_params)
      if @task.save
          flash[:success] = 'タスクが正常に投稿されました'
          redirect_to root_url
      else
          @tasks = current_user.tasks.order(id: :desc).page(params[:page])
          flash.now[:danger] = 'タスクが投稿されませんでした'
          render :new
      end
  end

  def edit
  end

  def update
      if @task.update(task_params)
          flash[:success] = 'タスクが正常に更新されました'
          redirect_to @task
      else
          flash.now[:danger] = 'タスクが更新されませんでした'
          render :edit
      end
  end

  def destroy
      @task.destroy
      flash[:success] = 'タスクは正常に削除されました'
      redirect_to root_url
  end
  
  private
  
  #Strong Parameter
  def task_params
      params.require(:task).permit(:content, :status)
  end
  
  def correct_task
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class ='container'>
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local:true) do |f| %>
    
    <%= render 'layouts/error_messages', model: f.object %><%# エラーメッセージをrenderで呼び出す%>
    
    <div><%= f.label :content, 'タスク' %><%= f.text_field :content %></div>
    <div><%= f.label :status, 'ステータス' %><%= f.text_field :status %></div>
    <%= f.submit '編集完了' %>
    
<% end %>

app/views/tasks/edit.html.erb
<h1>タスクの編集ページ</h1>
<%= render 'form', task: @task %>
<%= link_to '一覧に戻る', tasks_path %>
<%#= render 'form', task: @task.id  .id不要       %>

app/views/tasks/index.html.erb
<p>ログイン完了ユーザー: <%= current_user.name %>....<%= @tasks.count %>個のタスク</p>
<h1><%= current_user.name %>さんのタスク一覧</h1>
<table border="1">
    <thead>
        <tr>
            <th>タスク</th>
            <th>ステータス</th>
            <th>登録日時</th>
            <th>詳細</th>
            <th>削除</th>
        </tr>
    </thead>
    <tbody>
        <% @tasks.each do |task| %>
        <tr>
            <th><%= task.content %></th>
            <th><%= task.status %></th>
            <th><%= task.created_at %></th>
            <th><%= link_to '詳細/編集',task %></th>
            <%# if current_user == task.user %>
                <th><%= link_to "Delete", task, method: :delete, data: {confirm:"You sure?" }, class: 'btn' %></th>
            <%# end %>
        </tr>
        <% end %>
    </tbody>
</table>    
<ul>
    <li><%= link_to '新規タスクの投稿', new_task_path %></li>
    <li><%= link_to 'Logout', logout_path, method: :delete %></li>
</ul>

app/views/tasks/new.html.erb
<h1>新規タスク作成ページ</h1>

<%= render 'form', task: @task %>
<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<!--<!DOCTYPE html>
<html lang="ja">-->
<h1><%= current_user.name %>さんのタスク詳細</h1>
<!--  @task.id だと タスク総数が表示される。 -->
<table border="1">
    <thead>
        <tr>
            <th>タスク</th>
            <th>ステータス</th>
            <th>登録日時</th>
            <th>編集</th>
            <th>削除</th>
      </tr>
    </thead>
    <tbody>
        <tr>
            <th><%= @task.content %></th>
            <th><%= @task.status %></th>
            <th><%= @task.created_at %></th>
            <th><%= link_to '編集',edit_task_path(@task) %></th>
            <%# if current_user == @task.user %>
            <th><%= link_to "Delete", @task, method: :delete, data: {confirm:"You sure?" }, class: 'btn' %></th>
            <%# end %>
        </tr>
</table>
<ul>
    <li><%= link_to '新規タスクの投稿', new_task_path %></li>
    <li><%= link_to '一覧に戻る', tasks_path %></li>
    <li><%= link_to 'Logout', logout_path, method: :delete %></li>
</ul>    

app/views/users/_users.html.erb
<% if users.any? %>
    <% users.each do |user| %>
        <%= user.name %>
        <p><%= link_to 'view profile', user_path(user) %></p>
    <% end %>
  <%= paginate users %>
<% end %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="ja">
<h1>Sign up</h1>
    <%= form_with(model: @user, local: true) do |f| %>
    <ul>  
        <%= render 'layouts/error_messages', model: f.object %>
        
        <li><%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %></li>

        <li><%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %></li>

        <li><%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %></li>

        <li><%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %></li>
      

        <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
      </ul>
    <% end %>

<ul>
    <li><%= link_to 'loginページへ戻る', root_url %></li>
</ul>